from __future__ import annotations

import argparse
import getpass
import os
import shlex
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import httpx

from .client import CintaraClient
from .graph import CintaraGuard


DEFAULT_POLICY_URL = "https://platform.cintara.io/policy"
DEFAULT_REGISTRY_URL = "https://platform.cintara.io/registry"
DEFAULT_GATEWAY_URL = "https://gateway.cintara.io"
DEFAULT_TOOL_NAME = "send_email"


@dataclass(frozen=True)
class InitConfig:
    agent_id: str
    tenant_id: str
    policy_url: str
    registry_url: str
    gateway_url: str
    api_token: str
    tool_name: str = DEFAULT_TOOL_NAME


def _clean_url(value: str) -> str:
    return value.strip().rstrip("/")


def _quote(value: str) -> str:
    return shlex.quote(value)


def _is_placeholder(value: str) -> bool:
    return not value or value.startswith("<") or value.endswith(">")


def _prompt(label: str, current: str | None = None, *, secret: bool = False) -> str:
    if current:
        return current
    if not sys.stdin.isatty():
        return ""
    prompt = f"{label}: "
    if secret:
        return getpass.getpass(prompt).strip()
    return input(prompt).strip()


def build_env_file(config: InitConfig) -> str:
    return "\n".join(
        [
            "# Cintara LangGraph configuration",
            "# Load with: source .env.cintara",
            f"export CINTARA_POLICY_URL={_quote(config.policy_url)}",
            f"export CINTARA_REGISTRY_URL={_quote(config.registry_url)}",
            f"export CINTARA_GATEWAY_URL={_quote(config.gateway_url)}",
            f"export CINTARA_API_TOKEN={_quote(config.api_token)}",
            f"export CINTARA_TENANT_ID={_quote(config.tenant_id)}",
            f"export CINTARA_AGENT_ID={_quote(config.agent_id)}",
            f"export CINTARA_DEMO_TOOL_NAME={_quote(config.tool_name)}",
            "",
        ]
    )


def build_guard_file() -> str:
    return textwrap.dedent(
        '''
        """Small Cintara helper for LangGraph workflows.

        Generated by `cintara-langgraph init`.
        Keep Cintara tokens server-side. Do not import this file in browser code.
        """

        from __future__ import annotations

        import os

        from cintara_langgraph import CintaraGuard

        try:
            from langgraph.graph import END
        except ImportError:  # Allows importing this file before LangGraph is installed.
            END = "__end__"


        def build_cintara_guard(*, interrupt_on_approval: bool = False) -> CintaraGuard:
            return CintaraGuard(
                agent_id=os.environ["CINTARA_AGENT_ID"],
                interrupt_on_approval=interrupt_on_approval,
            )


        def add_cintara_guard(
            builder,
            *,
            tools_node: str = "tools",
            approval_node: str | None = None,
            end_node=END,
            interrupt_on_approval: bool = False,
        ) -> CintaraGuard:
            """Add Cintara as the pre-tool guard node.

            Routes:
            - allow: continue to the tool execution node
            - approval: route to approval_node if provided, otherwise end
            - deny/error: end safely
            """

            guard = build_cintara_guard(interrupt_on_approval=interrupt_on_approval)
            builder.add_node("cintara", guard)
            builder.add_conditional_edges(
                "cintara",
                guard.route,
                {
                    "allow": tools_node,
                    "approval": approval_node or end_node,
                    "deny": end_node,
                    "error": end_node,
                },
            )
            return guard
        '''
    ).lstrip()


def build_smoke_test_file() -> str:
    return textwrap.dedent(
        '''
        from __future__ import annotations

        import os
        import shlex
        import sys
        from pathlib import Path

        from cintara_langgraph import CintaraGuard


        def load_env(path: str = ".env.cintara") -> None:
            env_path = Path(path)
            if not env_path.exists():
                return
            for raw_line in env_path.read_text(encoding="utf-8").splitlines():
                line = raw_line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = shlex.split(line)
                if parts and parts[0] == "export":
                    parts = parts[1:]
                if not parts or "=" not in parts[0]:
                    continue
                key, value = parts[0].split("=", 1)
                os.environ.setdefault(key, value)


        def main() -> int:
            load_env()
            guard = CintaraGuard(agent_id=os.environ["CINTARA_AGENT_ID"])
            result = guard(
                {
                    "tool_call": {
                        "name": os.getenv("CINTARA_DEMO_TOOL_NAME", "send_email"),
                        "args": {
                            "to_email": "customer@example.com",
                            "body": "Hello from LangGraph.",
                            "amount": 7000,
                        },
                    },
                    "user_id": "langgraph-quickstart-user",
                    "tool_risk_tier": "WRITE",
                    "session_context": {
                        "user_email": "langgraph-quickstart@example.com",
                        "user_roles": ["tenant_admin"],
                        "request_ip": "127.0.0.1",
                    },
                }
            )
            decision = result["cintara"]
            print("Cintara route:", decision.get("route"))
            print("Cintara action:", decision.get("action"))
            print("Reason:", decision.get("reason"))
            if decision.get("request_id"):
                print("Request id:", decision["request_id"])
            return 2 if decision.get("route") == "error" else 0


        if __name__ == "__main__":
            raise SystemExit(main())
        '''
    ).lstrip()


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = shlex.split(line)
        if parts and parts[0] == "export":
            parts = parts[1:]
        if not parts or "=" not in parts[0]:
            continue
        key, value = parts[0].split("=", 1)
        values[key] = value
    return values


def write_init_files(project_dir: Path, config: InitConfig, *, overwrite: bool = False) -> list[Path]:
    project_dir.mkdir(parents=True, exist_ok=True)
    files = {
        ".env.cintara": build_env_file(config),
        "cintara_guard.py": build_guard_file(),
        "cintara_smoke_test.py": build_smoke_test_file(),
    }
    written: list[Path] = []
    for relative_path, content in files.items():
        path = project_dir / relative_path
        if path.exists() and not overwrite:
            continue
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def _api_base(url: str) -> str:
    cleaned = _clean_url(url)
    if cleaned.endswith("/api/v1"):
        return cleaned
    return f"{cleaned}/api/v1"


def _response_error_message(response: httpx.Response) -> str:
    try:
        detail = response.json().get("detail")
    except Exception:
        detail = None
    if isinstance(detail, str):
        return detail
    if detail:
        return str(detail)
    return response.text or f"HTTP {response.status_code}"


def _collect_self_service_config(args: argparse.Namespace, registry_url: str) -> InitConfig:
    developer_email = _prompt(
        "Developer email",
        args.developer_email or os.environ.get("CINTARA_DEVELOPER_EMAIL"),
    )
    if not developer_email:
        print("Developer email is required when using --onboarding-code.", file=sys.stderr)
        raise SystemExit(2)

    api_base = _api_base(registry_url)
    onboarding_code = args.onboarding_code.strip()
    start_url = f"{api_base}/langgraph/onboarding/{onboarding_code}/start"
    complete_url = f"{api_base}/langgraph/onboarding/{onboarding_code}/complete"

    try:
        with httpx.Client(timeout=15.0) as client:
            start_response = client.post(start_url, json={"developer_email": developer_email})
            if start_response.status_code >= 400:
                print(f"Cintara onboarding failed: {_response_error_message(start_response)}", file=sys.stderr)
                raise SystemExit(2)
            start_payload = start_response.json()
            print(
                "Verification code sent to "
                f"{start_payload.get('developer_email', developer_email)}."
            )
            verification_code = _prompt("Verification code", args.verification_code)
            if not verification_code:
                print("Verification code is required to finish onboarding.", file=sys.stderr)
                raise SystemExit(2)
            complete_response = client.post(
                complete_url,
                json={
                    "developer_email": developer_email,
                    "verification_code": verification_code,
                },
            )
            if complete_response.status_code >= 400:
                print(f"Cintara onboarding failed: {_response_error_message(complete_response)}", file=sys.stderr)
                raise SystemExit(2)
            payload = complete_response.json()
    except httpx.RequestError as exc:
        print(f"Cintara onboarding failed: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc

    return InitConfig(
        agent_id=str(payload["agent_id"]),
        tenant_id=str(payload["tenant_id"]),
        policy_url=_clean_url(str(payload["policy_url"])),
        registry_url=_clean_url(str(payload["registry_url"])),
        gateway_url=_clean_url(str(payload["gateway_url"])),
        api_token=str(payload["access_token"]),
        tool_name=args.tool_name or os.environ.get("CINTARA_DEMO_TOOL_NAME") or DEFAULT_TOOL_NAME,
    )


def _collect_config(args: argparse.Namespace) -> InitConfig:
    env = os.environ
    policy_url = _clean_url(args.policy_url or env.get("CINTARA_POLICY_URL") or DEFAULT_POLICY_URL)
    registry_url = _clean_url(args.registry_url or env.get("CINTARA_REGISTRY_URL") or DEFAULT_REGISTRY_URL)
    gateway_url = _clean_url(args.gateway_url or env.get("CINTARA_GATEWAY_URL") or DEFAULT_GATEWAY_URL)

    if args.onboarding_code:
        return _collect_self_service_config(args, registry_url)

    agent_id = _prompt("Cintara agent id", args.agent_id or env.get("CINTARA_AGENT_ID"))
    tenant_id = _prompt("Cintara tenant id", args.tenant_id or env.get("CINTARA_TENANT_ID"))
    api_token = _prompt(
        "Cintara runtime token from your admin",
        args.api_token or env.get("CINTARA_API_TOKEN"),
        secret=True,
    )

    if not agent_id:
        agent_id = "<agent-id>"
    if not tenant_id:
        tenant_id = "<tenant-id>"
    if not api_token:
        api_token = "<cintara-runtime-token>"

    return InitConfig(
        agent_id=agent_id,
        tenant_id=tenant_id,
        policy_url=policy_url,
        registry_url=registry_url,
        gateway_url=gateway_url,
        api_token=api_token,
        tool_name=args.tool_name or env.get("CINTARA_DEMO_TOOL_NAME") or DEFAULT_TOOL_NAME,
    )


def _run_smoke_test(config: InitConfig) -> int:
    if _is_placeholder(config.api_token) or _is_placeholder(config.agent_id) or _is_placeholder(config.tenant_id):
        print("Skipping smoke test because one or more required values are placeholders.")
        print("Ask your Cintara admin for a generated LangGraph setup command or runtime token.")
        return 0

    try:
        client = CintaraClient(
            policy_url=config.policy_url,
            gateway_url=config.gateway_url,
            token=config.api_token,
            tenant_id=config.tenant_id,
        )
        guard = CintaraGuard(agent_id=config.agent_id, client=client)
        result = guard(
            {
                "tool_call": {
                    "name": config.tool_name,
                    "args": {
                        "to_email": "customer@example.com",
                        "body": "Hello from LangGraph.",
                        "amount": 7000,
                    },
                },
                "user_id": "langgraph-quickstart-user",
                "tool_risk_tier": "WRITE",
                "session_context": {
                    "user_email": "langgraph-quickstart@example.com",
                    "user_roles": ["tenant_admin"],
                    "request_ip": "127.0.0.1",
                },
            }
        )
    except Exception as exc:
        print(f"Smoke test could not reach Cintara: {exc}")
        print("Files were still created. Re-run `cintara-langgraph test` after checking the values.")
        return 0

    decision = result["cintara"]
    print("Smoke test reached Cintara.")
    print(f"Route: {decision.get('route')}")
    print(f"Action: {decision.get('action')}")
    print(f"Reason: {decision.get('reason')}")
    return 0


def run_init(args: argparse.Namespace) -> int:
    project_dir = Path(args.project_dir).expanduser().resolve()
    config = _collect_config(args)
    written = write_init_files(project_dir, config, overwrite=args.overwrite)

    if written:
        print("Created:")
        for path in written:
            print(f"  - {path.relative_to(project_dir)}")
    else:
        print("No files changed. Use --overwrite to regenerate existing files.")

    if not args.skip_smoke_test:
        _run_smoke_test(config)

    print("\nNext:")
    print("  source .env.cintara")
    print("  cintara-langgraph test")
    print("  import add_cintara_guard from cintara_guard.py in your LangGraph workflow")
    return 0


def run_test(args: argparse.Namespace) -> int:
    project_dir = Path(args.project_dir).expanduser().resolve()
    values = load_env_file(project_dir / ".env.cintara")
    for key, value in values.items():
        os.environ.setdefault(key, value)

    tool_name = args.tool_name or os.getenv("CINTARA_DEMO_TOOL_NAME") or DEFAULT_TOOL_NAME
    try:
        guard = CintaraGuard(agent_id=os.environ["CINTARA_AGENT_ID"])
        result = guard(
            {
                "tool_call": {
                    "name": tool_name,
                    "args": {
                        "to_email": args.to_email,
                        "body": "Hello from LangGraph.",
                        "amount": args.amount,
                    },
                },
                "user_id": args.user_id,
                "tool_risk_tier": args.tool_risk_tier,
                "session_context": {
                    "user_email": args.user_email,
                    "user_roles": [args.user_role],
                    "request_ip": args.request_ip,
                },
            }
        )
    except KeyError as exc:
        print(f"Missing environment value: {exc}")
        print("Run `cintara-langgraph init` or `source .env.cintara` first.")
        return 2
    except Exception as exc:
        print(f"Cintara smoke test failed: {exc}")
        return 2

    decision = result["cintara"]
    print("Cintara route:", decision.get("route"))
    print("Cintara action:", decision.get("action"))
    print("Reason:", decision.get("reason"))
    if decision.get("request_id"):
        print("Request id:", decision["request_id"])
    return 2 if decision.get("route") == "error" else 0


def run_install(args: argparse.Namespace) -> int:
    package = (
        "cintara-langgraph[langgraph] @ "
        "git+https://github.com/Cintaraio/cintara-langgraph.git"
    )
    return subprocess.call([sys.executable, "-m", "pip", "install", package])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cintara-langgraph",
        description="Initialize and test Cintara LangGraph onboarding.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create local Cintara LangGraph onboarding files.")
    init_parser.add_argument("--agent-id")
    init_parser.add_argument("--tenant-id")
    init_parser.add_argument("--policy-url")
    init_parser.add_argument("--registry-url")
    init_parser.add_argument("--gateway-url")
    init_parser.add_argument("--api-token")
    init_parser.add_argument("--onboarding-code")
    init_parser.add_argument("--developer-email")
    init_parser.add_argument("--verification-code")
    init_parser.add_argument("--tool-name", default=DEFAULT_TOOL_NAME)
    init_parser.add_argument("--project-dir", default=".")
    init_parser.add_argument("--overwrite", action="store_true")
    init_parser.add_argument("--skip-smoke-test", action="store_true")
    init_parser.set_defaults(func=run_init)

    test_parser = subparsers.add_parser("test", help="Run a Cintara decision smoke test.")
    test_parser.add_argument("--project-dir", default=".")
    test_parser.add_argument("--tool-name")
    test_parser.add_argument("--to-email", default="customer@example.com")
    test_parser.add_argument("--amount", type=float, default=7000)
    test_parser.add_argument("--user-id", default="langgraph-quickstart-user")
    test_parser.add_argument("--user-email", default="langgraph-quickstart@example.com")
    test_parser.add_argument("--user-role", default="tenant_admin")
    test_parser.add_argument("--request-ip", default="127.0.0.1")
    test_parser.add_argument("--tool-risk-tier", default="WRITE")
    test_parser.set_defaults(func=run_test)

    install_parser = subparsers.add_parser("install", help="Install the public GitHub package with LangGraph extras.")
    install_parser.set_defaults(func=run_install)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
